In [1]:
from utils_articles import TopicTrain

In [ ]:
TopicTrain('model')._loadArticles('data')

In [ ]:
TopicTrain('model').train()

In [3]:
import os
import pandas as pd
def _loadArticles(path):
        cat_article = []
        for subdir, dirs, files in os.walk(path):
            #print(subdir,dirs,files)
            for file in files:
                if '.txt' in file:
                    category = subdir.split('/')[-1]
                    f = open(os.path.join(subdir, file),'r')
                    lines = f.readlines()
                    lines = ' '.join(lines).replace('\n','')
                    #list of lists: [category,article]
                    cat_article.append([category,lines])
                    f.close()
        data = pd.DataFrame(cat_article)
        data.columns = ['category','article']
        return data

In [ ]:
_loadArticles('data')

In [2]:
TopicTrain().train()

In [1]:
import os
import pathlib
import joblib

model_path = os.path.join(str(pathlib.Path().absolute()), "model")
model_file = model_path + "/rm_tfidf.pkl"
model = joblib.load(model_file)

In [4]:
target_art = _loadArticles('test_articles')
target_art

category                                            article
0  test_articles  Barclays boss Jes Staley is "shell-shocked, an...
1  test_articles  For nearly seven months, through the regular s...
2  test_articles  Tennessee Titans running back Derrick Henry su...
3  test_articles  There will still be a Facebook, and an Instagr...

In [133]:
inp = target_art['article'].values[1]
inp

"For nearly seven months, through the regular season and the early rounds of the playoffs, the Houston Astros featured the best offense in baseball. It was the highest-scoring, best-balanced, most unsolvable attack in the majors.  The Astros hit for power. They hit for average. They walked the fine line between discipline and aggression: They were the best two-strike hitting team in the big leagues. In an era when so much of the battle is decided by the team that wins the strike zone, the Astros' batsmen generally won the strike zone."

In [134]:
import numpy as np
inp_arr = np.array(inp)
inp_arr

array("For nearly seven months, through the regular season and the early rounds of the playoffs, the Houston Astros featured the best offense in baseball. It was the highest-scoring, best-balanced, most unsolvable attack in the majors.  The Astros hit for power. They hit for average. They walked the fine line between discipline and aggression: They were the best two-strike hitting team in the big leagues. In an era when so much of the battle is decided by the team that wins the strike zone, the Astros' batsmen generally won the strike zone.",
      dtype='<U539')

In [153]:
pred = model.predict([inp])
proba = model.predict_proba([inp])
print(pred)
proba[0]

['sport']


array([0.14, 0.25, 0.03, 0.58, 0.  ])

In [136]:
print(model.predict(target_art['article'].values))
model.predict_proba(target_art['article'])

['business' 'sport' 'sport' 'business']


array([[0.35, 0.23, 0.2 , 0.16, 0.06],
       [0.14, 0.25, 0.03, 0.58, 0.  ],
       [0.08, 0.05, 0.02, 0.81, 0.04],
       [0.38, 0.08, 0.16, 0.07, 0.31]])

In [152]:
np.where(model.classes_ == pred)[0][0]

3

In [109]:
import pandas as pd
proba_df = pd.DataFrame(proba[0], index = model.classes_, columns = ['Proba'])
proba_df

Proba
business        0.35
entertainment   0.23
politics        0.20
sport           0.16
tech            0.06

In [78]:
import numpy as np
inp_imp = model.steps[1][1].feature_importances_
sorted_inp = np.sort(inp_imp)[::-1]
sorted_inp.shape

(10252,)

In [36]:
for tree in model.steps[1][1].estimators_:
    print(tree.feature_importances_)

[0.         0.         0.         ... 0.         0.         0.00169175]
[0.         0.         0.         ... 0.         0.         0.00097573]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.00089405]
[0.         0.         0.         ... 0.         0.         0.00647277]
[0.         0.         0.         ... 0.         0.         0.02065267]
[0.         0.         0.         ... 0.         0.         0.01416708]
[0.         0.         0.         ... 0.         0.         0.00135503]
[0. 0. 0. ... 0. 0. 0.]
[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 6.0818187e-06]
[0.         0.         0.         ... 0.         0.         0.02510455]
[0.         0.         0.         ... 0.         0.         0.01969459]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.00106961]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.         0.         ... 0.         0.         0.0050622

In [79]:
len(model.steps[0][1].vocabulary_)#Este es todo el corpus de palabras de nuestro modelo. 

10252

In [80]:
import matplotlib.pyplot as plt
sorted_idx = model.steps[1][1].feature_importances_.argsort()
sorted_idx = sorted_idx[::-1]
sorted_idx
#plt.barh()

array([3814, 4307, 8815, ..., 3853, 3855, 5125])

In [66]:
def get_key(val):
    for key, value in model.steps[0][1].vocabulary_.items():
         if val == value:
             return key

In [81]:
get_key(3814)
get_key(4307)
get_key(8815)

'star'

In [131]:
model.steps[0][1].vocabulary_

{'ad': 703,
 'sale': 8130,
 'boost': 1538,
 'time': 9349,
 'warner': 9963,
 'profit': 7347,
 'quarterly': 7485,
 'medium': 6052,
 'giant': 4209,
 'jump': 5320,
 '76': 542,
 '1.13bn': 34,
 '£': 10251,
 '600': 497,
 'm': 5807,
 'month': 6262,
 'december': 2745,
 'year': 10196,
 'early': 3260,
 'firm': 3846,
 'big': 1413,
 'investor': 5116,
 'google': 4295,
 'benefit': 1368,
 'high': 4612,
 'speed': 8711,
 'internet': 5079,
 'connection': 2345,
 'advert': 748,
 'fourth': 3979,
 'quarter': 7484,
 'rise': 7973,
 '2': 253,
 'buoy': 1717,
 'gain': 4102,
 'offset': 6631,
 'dip': 2980,
 'bros': 1666,
 'user': 9763,
 'aol': 981,
 'friday': 4035,
 '8': 548,
 'search': 8263,
 'engine': 3432,
 'business': 1741,
 'mix': 6217,
 'fortune': 3968,
 'lose': 5751,
 'subscriber': 8969,
 'low': 5764,
 'precede': 7229,
 'company': 2240,
 'underlie': 9620,
 'exceptional': 3578,
 'item': 5170,
 'strong': 8937,
 'advertising': 752,
 'revenue': 7913,
 'hope': 4689,
 'increase': 4902,
 'offer': 6623,
 'online': 6

In [55]:
list(model.steps[0][1].vocabulary_)[8815]

'poison'

In [57]:
avgDists = np.array([1, 8, 6, 9, 4])
ids = avgDists.argsort()
ids[::-1]

array([3, 1, 2, 4, 0])

In [110]:
from utils_articles import spacy_tokenizer
tokens = spacy_tokenizer(inp)
tokens

['barclays',
 'boss',
 'jes',
 'staley',
 'shell',
 'shocked',
 'angry',
 'upset',
 'conclusion',
 'probe',
 'link',
 'sex',
 'offender',
 'jeffrey',
 'epstein',
 'lead',
 'sudden',
 'exit',
 'bank',
 'insider',
 'close',
 'mr',
 'staley',
 'surprise',
 'city',
 'regulator',
 'finding',
 'investigate',
 'mr',
 'staley',
 'link',
 'dead',
 'financier',
 'close',
 'think',
 'barclays',
 'aware',
 'conclusion',
 'probe',
 'mr',
 'staley',
 'intention',
 'contest',
 'heart',
 'mr',
 'staley',
 'departure',
 'apparently',
 'perceive',
 'inconsistency',
 'account',
 'board',
 'relationship',
 'epstein',
 'evidence',
 'regulator',
 'mr',
 'staley',
 'insist',
 'epstein',
 'important',
 'client',
 'jp',
 'morgan',
 'mr',
 'staley',
 'work',
 'number',
 'year',
 'contact',
 'regularly',
 'dealing',
 'ground',
 'describe',
 'professional',
 'bbc',
 'understand',
 'regulator',
 'view',
 'volume',
 'tone',
 'email',
 'suggest',
 'close',
 'relationship',
 'purely',
 'professional',
 'barclays',
 '

In [111]:
arr = []
for token in tokens:
    idx = model.steps[0][1].vocabulary_.get(token)
    #print(idx)
    if idx is not None: 
        fimp = model.steps[1][1].feature_importances_[idx]
        #print(token, idx, fimp)
        arr.append({'TOKEN':token, 'Importance':fimp})
    
df_imp = pd.DataFrame(arr)

In [120]:
new_df = df_imp.groupby(['TOKEN','Importance']).count().sort_values(by = 'Importance',ascending = False).head(10)
new_df

Empty DataFrame
Columns: []
Index: [(mr, 0.00688529930263224), (include, 0.004003535748775534), (bank, 0.0029566067946739535), (report, 0.001529101828657923), (year, 0.0015056122074791334), (executive, 0.0012516035797902735), (boss, 0.001222282509470238), (work, 0.0012098263465522572), (month, 0.0009696104244819053), (state, 0.0009663458550156176)]

In [130]:
df_imp.groupby(by = ['TOKEN','Importance'],  as_index=False).sum().sort_values(by = 'Importance',ascending = False).head(10)

TOKEN  Importance
54         mr    0.006885
38    include    0.004004
7        bank    0.002957
67     report    0.001529
86       year    0.001506
31  executive    0.001252
12       boss    0.001222
85       work    0.001210
52      month    0.000970
73      state    0.000966

Try multinomial NB for classifying articles

https://colab.research.google.com/drive/1HCi-1hxsbYYmT8jbAsIRHIBaJZzpr93U#scrollTo=ruMuNzOe-QuL